version: '2'

services:
  influxdb:
    image: influxdb:1.0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8088:8088"
      - "25826:25826/udp"
    volumes:
      - 1f27b3e868c72a45133aff32897ce22799e5ab321ea8b8170f435474167b8f63:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    restart: always
  grafana:
    image: grafana/grafana:3.1.1
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
    restart: always
volumes:
  1f27b3e868c72a45133aff32897ce22799e5ab321ea8b8170f435474167b8f63:
    external:
      true
